package com.asusoft.calendar.util.objects

object PreferenceKey {

    const val SELECTED_CALENDAR_TYPE = "KEY_SELECTED_CALENDAR_TYPE"

    // 상단 바
    const val CALENDAR_HEADER_FONT_SIZE = "KEY_CALENDAR_HEADER_FONT_SIZE"
    const val CALENDAR_HEADER_DEFAULT_FONT_SIZE = 18F

    // 월간 캘린더
    // TODO: - 분할 작업 -> header, day, item, counter
    const val MONTH_CALENDAR_DRAG_AND_DROP = "KEY_MONTH_CALENDAR_DRAG_AND_DROP"
    const val DRAG_AND_DROP_DEFAULT = true

    const val MONTH_CALENDAR_HEADER_FONT_SIZE = "KEY_MONTH_CALENDAR_HEADER_FONT_SIZE"
    const val MONTH_CALENDAR_HEADER_DEFAULT_FONT_SIZE = 12F

    const val MONTH_CALENDAR_DAY_FONT_SIZE = "KEY_MONTH_CALENDAR_DAY_FONT_SIZE"
    const val MONTH_CALENDAR_DAY_DEFAULT_FONT_SIZE = 12F

    const val MONTH_CALENDAR_EVENT_FONT_SIZE = "KEY_MONTH_CALENDAR_EVENT_FONT_SIZE"
    const val MONTH_CALENDAR_EVENT_DEFAULT_FONT_SIZE = 11F

    const val MONTH_CALENDAR_COUNTER_FONT_SIZE = "KEY_MONTH_CALENDAR_COUNTER_FONT_SIZE"
    const val MONTH_CALENDAR_COUNTER_DEFAULT_FONT_SIZE = 11F


    // 주간 캘린더
    const val WEEK_CALENDAR_HEADER_FONT_SIZE = "KEY_WEEK_CALENDAR_HEADER_FONT_SIZE"
    const val WEEK_CALENDAR_HEADER_DEFAULT_FONT_SIZE = 15F

    const val WEEK_CALENDAR_EVENT_FONT_SIZE = "KEY_WEEK_CALENDAR_EVENT_FONT_SIZE"
    const val WEEK_CALENDAR_EVENT_DEFAULT_FONT_SIZE = 14F


    // 일일 이벤트 팝업 - 폰트 사이즈
    const val DAY_CALENDAR_HEADER_FONT_SIZE = "KEY_DAY_CALENDAR_HEADER_FONT_SIZE"
    const val DAY_CALENDAR_HEADER_DEFAULT_FONT_SIZE = 16F

    const val DAY_CALENDAR_ITEM_FONT_SIZE = "KEY_DAY_CALENDAR_ITEM_FONT_SIZE"
    const val DAY_CALENDAR_ITEM_DEFAULT_FONT_SIZE = 15F


    // 화면 방향
    const val CALENDAR_ORIENTATION = "KEY_CALENDAR_ORIENTATION"
    const val CALENDAR_DEFAULT_ORIENTATION = 1
}